name: LifeMemo
options:
  bundleIdPrefix: com.lifememo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    GENERATE_INFOPLIST_FILE: false
    INFOPLIST_FILE: Resources/Info.plist

targets:
  LifeMemo:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Presentation
      - path: Domain
      - path: Infrastructure
      - path: Resources
        excludes:
          - "*.xcassets"
    resources:
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifememo.app
        PRODUCT_NAME: LifeMemo
        MARKETING_VERSION: "0.2.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
    info:
      path: Resources/Info.plist
    entitlements:
      path: Resources/LifeMemo.entitlements
