name: LifeMemo
options:
  bundleIdPrefix: com.lifememo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    GENERATE_INFOPLIST_FILE: false
    INFOPLIST_FILE: Resources/Info.plist

targets:
  LifeMemo:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Presentation
      - path: Domain
      - path: Infrastructure
      - path: Resources
        excludes:
          - "*.xcassets"
    resources:
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifememo.app
        PRODUCT_NAME: LifeMemo
        MARKETING_VERSION: "0.3.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CODE_SIGNING_ALLOWED[sdk=iphonesimulator*]: NO
        CODE_SIGNING_REQUIRED[sdk=iphonesimulator*]: NO
    info:
      path: Resources/Info.plist
      properties:
        UILaunchScreen: {}
        UIBackgroundModes:
          - audio
        NSMicrophoneUsageDescription: "LifeMemo uses the microphone to record voice memos."
        NSSpeechRecognitionUsageDescription: "LifeMemo uses speech recognition to transcribe recorded audio to text."
        NSLocationWhenInUseUsageDescription: "LifeMemo uses location to tag recordings with where they were made."
    entitlements:
      path: Resources/LifeMemo.entitlements

  LifeMemoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LifeMemoTests
    dependencies:
      - target: LifeMemo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifememo.app.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LifeMemo.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LifeMemo"
        BUNDLE_LOADER: "$(TEST_HOST)"
        DEVELOPMENT_TEAM: ""
        CODE_SIGNING_ALLOWED[sdk=iphonesimulator*]: NO
        CODE_SIGNING_REQUIRED[sdk=iphonesimulator*]: NO
